export declare const BaseColors: {
    Blue: string;
    Red: string;
    Green: string;
    Purple: string;
    Cyan: string;
    Orange: string;
    "Light Blue": string;
    Lilac: string;
    "Light Green": string;
    Brown: string;
    Black: string;
    Gray: string;
    Pink: string;
    "Dark Blue": string;
};
export declare const AdditionalColors: {
    "Indian Red": string;
    "Green 2": string;
    "Green 3": string;
    "Dark Turquoise": string;
    "Dark Violet": string;
    "Pink 2": string;
};
declare let ColorPalette: {
    "Indian Red": string;
    "Green 2": string;
    "Green 3": string;
    "Dark Turquoise": string;
    "Dark Violet": string;
    "Pink 2": string;
    Blue: string;
    Red: string;
    Green: string;
    Purple: string;
    Cyan: string;
    Orange: string;
    "Light Blue": string;
    Lilac: string;
    "Light Green": string;
    Brown: string;
    Black: string;
    Gray: string;
    Pink: string;
    "Dark Blue": string;
};
export declare const ColorPaletteArray: string[];
export default ColorPalette;
export declare const AllColorPalettes: {
    Redash: {
        "Indian Red": string;
        "Green 2": string;
        "Green 3": string;
        "Dark Turquoise": string;
        "Dark Violet": string;
        "Pink 2": string;
        Blue: string;
        Red: string;
        Green: string;
        Purple: string;
        Cyan: string;
        Orange: string;
        "Light Blue": string;
        Lilac: string;
        "Light Green": string;
        Brown: string;
        Black: string;
        Gray: string;
        Pink: string;
        "Dark Blue": string;
    };
    Viridis: {
        1: string;
        2: string;
        3: string;
        4: string;
        5: string;
        6: string;
        7: string;
        8: string;
        9: string;
        10: string;
        11: string;
        12: string;
        13: string;
        14: string;
        15: string;
        16: string;
        17: string;
    };
    "Tableau 10": {
        1: string;
        2: string;
        3: string;
        4: string;
        5: string;
        6: string;
        7: string;
        8: string;
        9: string;
        10: string;
    };
    "D3 Category 10": {
        1: string;
        2: string;
        3: string;
        4: string;
        5: string;
        6: string;
        7: string;
        8: string;
        9: string;
        10: string;
    };
};
export declare const AllColorPaletteArrays: {
    Redash: string[];
    Viridis: string[];
    "Tableau 10": string[];
    "D3 Category 10": string[];
};
export declare const ColorPaletteTypes: {
    Redash: string;
    Viridis: string;
    "Tableau 10": string;
    "D3 Category 10": string;
};
