import Checkbox from "antd/lib/checkbox";
import withControlLabel, { ControlLabel } from "./withControlLabel";
import createTabbedEditor from "./createTabbedEditor";
import Section from "./Section";
import Switch from "./Switch";
import TextArea from "./TextArea";
import ContextHelp from "./ContextHelp";
export { Section, ControlLabel, Checkbox, Switch, TextArea, ContextHelp, withControlLabel, createTabbedEditor };
export declare const Select: ({ className, id, layout, label, labelProps, disabled, ...props }: any) => JSX.Element;
export declare const Input: ({ className, id, layout, label, labelProps, disabled, ...props }: any) => JSX.Element;
export declare const InputNumber: ({ className, id, layout, label, labelProps, disabled, ...props }: any) => JSX.Element;
export declare const ColorPicker: ({ className, id, layout, label, labelProps, disabled, ...props }: any) => JSX.Element;
export declare const TextAlignmentSelect: ({ className, id, layout, label, labelProps, disabled, ...props }: any) => JSX.Element;
